/**
 * Load Test - Queue-Based Execution
 * Story 4.1: Queue-Based Execution — BullMQ Integration (Task 8.7)
 *
 * Validates queue handles 100+ simultaneous jobs without crash.
 * Uses dependency injection (no real Redis required).
 */

const { QueueManager } = require('../../queue-manager');
const { QueueWorkerPool } = require('../../queue-worker');

/**
 * Creates a mock queue that stores jobs in-memory
 */
function createMockQueue() {
  const jobs = [];
  return {
    jobs,
    add: vi.fn().mockImplementation(async (name, data, opts) => {
      const job = {
        id: opts?.jobId || `job-${jobs.length + 1}`,
        name,
        data,
        opts,
        attemptsMade: 0,
        failedReason: null,
        timestamp: Date.now(),
        processedOn: null,
        finishedOn: null,
        remove: vi.fn(),
      };
      jobs.push(job);
      return job;
    }),
    getWaitingCount: vi.fn().mockImplementation(() => Promise.resolve(jobs.length)),
    getActiveCount: vi.fn().mockResolvedValue(0),
    getCompletedCount: vi.fn().mockResolvedValue(0),
    getFailedCount: vi.fn().mockResolvedValue(0),
    getDelayedCount: vi.fn().mockResolvedValue(0),
    getWaiting: vi.fn().mockImplementation(async () => jobs),
    getJob: vi.fn().mockImplementation(async (id) => jobs.find(j => j.id === id) || null),
    close: vi.fn(),
  };
}

describe('Queue Load Test — 100+ Simultaneous Jobs', () => {
  let queueManager;
  let workerPool;
  let mockOrchestrator;
  let mockQueue;
  let mockDLQQueue;
  let mockWorkerInstance;

  beforeEach(() => {
    mockQueue = createMockQueue();
    mockDLQQueue = createMockQueue();

    mockWorkerInstance = {
      on: vi.fn(),
      close: vi.fn().mockResolvedValue(undefined),
      id: 'load-test-worker',
    };

    const mockEventStore = { append: vi.fn() };

    queueManager = new QueueManager({
      eventStore: mockEventStore,
      queue: mockQueue,
      dlqQueue: mockDLQQueue,
    });

    mockOrchestrator = {
      execute: vi.fn().mockResolvedValue({
        runId: 'run-load',
        status: 'completed',
      }),
    };

    workerPool = new QueueWorkerPool({
      orchestrator: mockOrchestrator,
      eventStore: mockEventStore,
      createWorkerFn: vi.fn(() => mockWorkerInstance),
      queue: mockQueue,
      dlqQueue: mockDLQQueue,
    });
  });

  test('enqueue 100 jobs simultaneously without crash', async () => {
    const promises = Array.from({ length: 100 }, (_, i) =>
      queueManager.enqueue(`squad-${i % 10}`, {
        type: 'load-test',
        index: i,
      }, {
        priority: (i % 10) + 1,
      })
    );

    const results = await Promise.all(promises);

    expect(results).toHaveLength(100);
    expect(results.every(r => r.queued === true)).toBe(true);
    expect(results.every(r => typeof r.runId === 'string')).toBe(true);
    expect(mockQueue.jobs).toHaveLength(100);
  });

  test('all 100 jobs have unique runIds when pre-generated', async () => {
    // In production, runIds are pre-generated by SquadOrchestrator.loadSquad()
    // before enqueue — simulating that pattern here
    const promises = Array.from({ length: 100 }, (_, i) =>
      queueManager.enqueue('squad-copy', {
        type: 'load-test',
        index: i,
      }, {
        runId: `squad-copy-load-${i}`,
      })
    );

    const results = await Promise.all(promises);
    const runIds = results.map(r => r.runId);
    const uniqueRunIds = new Set(runIds);

    expect(uniqueRunIds.size).toBe(100);
    expect(runIds[0]).toBe('squad-copy-load-0');
    expect(runIds[99]).toBe('squad-copy-load-99');
  });

  test('workers process 100 jobs sequentially without crash', async () => {
    // Enqueue 100 jobs
    for (let i = 0; i < 100; i++) {
      await queueManager.enqueue('squad-copy', {
        type: 'load-test',
        index: i,
      });
    }

    expect(mockQueue.jobs).toHaveLength(100);

    // Start worker
    workerPool.start();

    // Process all jobs
    for (const job of mockQueue.jobs) {
      await workerPool.processJob(job);
    }

    expect(mockOrchestrator.execute).toHaveBeenCalledTimes(100);
    await workerPool.stop();
  });

  test('mixed priorities across 100 jobs are preserved', async () => {
    const promises = Array.from({ length: 100 }, (_, i) =>
      queueManager.enqueue(`squad-${i}`, {
        type: 'load-test',
      }, {
        priority: (i % 10) + 1,
      })
    );

    await Promise.all(promises);

    // Verify priorities are correctly set
    for (let i = 0; i < 100; i++) {
      const expectedPriority = (i % 10) + 1;
      expect(mockQueue.jobs[i].data.priority).toBe(expectedPriority);
      expect(mockQueue.jobs[i].opts.priority).toBe(expectedPriority);
    }
  });

  test('150 concurrent enqueues with varied squads', async () => {
    const squads = ['squad-copy', 'squad-ads', 'squad-email', 'squad-sms', 'squad-push'];
    const promises = Array.from({ length: 150 }, (_, i) =>
      queueManager.enqueue(squads[i % squads.length], {
        type: 'stress-test',
        index: i,
      }, {
        priority: Math.floor(Math.random() * 10) + 1,
        overrides: { batch: Math.floor(i / 30) },
      })
    );

    const results = await Promise.all(promises);

    expect(results).toHaveLength(150);
    expect(results.every(r => r.queued === true)).toBe(true);
    expect(mockQueue.jobs).toHaveLength(150);

    // Verify squad distribution
    const squadCounts = {};
    for (const job of mockQueue.jobs) {
      const sid = job.data.squadId;
      squadCounts[sid] = (squadCounts[sid] || 0) + 1;
    }
    expect(squadCounts['squad-copy']).toBe(30);
    expect(squadCounts['squad-ads']).toBe(30);
  });
});
